name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: '3 3 * * 2'  # 3:03 AM, every Tuesday

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - macos-13
        platform:
          - iOS
          - macOS
          - tvOS
          - watchOS
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Test Library
        uses: mxcl/xcodebuild@v2
        with:
          platform: ${{ matrix.platform }}
          action: test

      # - name: Build Examples/Demo
      #   uses: mxcl/xcodebuild@v2
      #   with:
      #     platform: ${{ matrix.platform }}
      #     swift: ~${{ matrix.swift }}
      #     action: build
      #     scheme: Demo
